usr/lib/linuxmint/mintinstall/mintinstall.py

This also fixes an issue where the category wasn't highlighted when selecting
it.

subcategories: Ensure the "All" category is selected initially

---

usr/lib/linuxmint/mintinstall/mintinstall.py

The flowbox is added again a few lines down. Remove a duplicate instance to
quiet some gtk warnings

loading: Don't attempt to add the add the same widget twice

---

usr/lib/linuxmint/mintinstall/mintinstall.py
usr/share/linuxmint/mintinstall/mintinstall.glade

* Add labels to the install/remove progress bar
* Add a label to the progress spinner when installing flatpak dependencies
* Flatpaks can be a bit slow to start installing. Switch to showing the
install progress bar sooner to give the user an indication that it's actually
working.

Make installation and removal a bit more user friendly

---

usr/lib/linuxmint/mintinstall/mintinstall.py
usr/share/linuxmint/mintinstall/mintinstall.glade

Users are having issues on monitors with a height of 768. Remove the unneeded
"Featured Application" label. Also reduce the height of the banner by 20px.
This brings the overall height to less than 700px.

Reduce the vertical size of the window

---

usr/lib/linuxmint/mintinstall/mintinstall.py

We look for the icon by package name first. Such as org.gnome.Calculator.
Failing that we will fallback to the more generic name of just calculator. This
will allow us to ship icons for these in our themes.

Change the logic a bit for finding flatpak icons

---

usr/share/linuxmint/mintinstall/categories/picks-kde.list
usr/share/linuxmint/mintinstall/categories/picks.list

Fix would be adding the latest version to upstream
http://flavio.tordini.org/minitube

 Remove minitube from editors picks as it is broken

---

usr/lib/linuxmint/mintinstall/mintinstall.py

We can use the "Content-Length" header from a HEAD request to quickly check the file size of the remote reviews.list and only download the whole file if it's different from the local reviews.list's file size.
This would save over 5 MBs (and growing) of network traffic if the local list is up to date.
[Small gist](https://gist.github.com/milangfx/8ce01d148e9cde95692057701f5b58e8) to check the load time of the different methods.

Use HEAD request to check new-reviews file size

---

usr/bin/mintinstall-fp-handler
usr/bin/mintinstall-remove-app
usr/bin/mintinstall-update-pkgcache
usr/lib/linuxmint/mintinstall/housekeeping.py
usr/lib/linuxmint/mintinstall/installer/_apt.py
usr/lib/linuxmint/mintinstall/installer/_flatpak.py
usr/lib/linuxmint/mintinstall/installer/cache.py
usr/lib/linuxmint/mintinstall/installer/dialogs.py
usr/lib/linuxmint/mintinstall/installer/installer.py
usr/lib/linuxmint/mintinstall/installer/pkgInfo.py
usr/lib/linuxmint/mintinstall/mintinstall-remove-app.py
usr/lib/linuxmint/mintinstall/mintinstall-update-pkgcache.py
usr/lib/linuxmint/mintinstall/mintinstall.py
usr/lib/linuxmint/mintinstall/misc.py
usr/lib/linuxmint/mintinstall/reviews.py
usr/share/applications/mintinstall-fp-handler.desktop
usr/share/glib-2.0/schemas/com.linuxmint.install.gschema.xml
usr/share/linuxmint/mintinstall/mintinstall.glade

Trying to simplify package handling in mintinstall so that all package types can be treated the same from a UI perspective.  This is accomplished, more or less, except for a few items shown in the package details view that there aren't equivalents for between apt and flatpaks.
See commits for more details.

Split ui code from package management

---

usr/share/linuxmint/mintinstall/mintinstall.glade

Gives us a small bit of space here:
So the icon isn't right against the window edge.

UI: Add a small margin between the application icon and window edge

---

usr/lib/linuxmint/mintinstall/installer/_flatpak.py
usr/lib/linuxmint/mintinstall/installer/cache.py
usr/lib/linuxmint/mintinstall/installer/installer.py
usr/lib/linuxmint/mintinstall/mintinstall.py

- Avoids problematic api where possible
- track installed apps more accurately (becomes an issue with multiple potential sources of apps)
- allow one-off installed flatpaks to be displayed and uninstalled (generate installed, but not cached, flatpaks at startup
various other.
Tested on flatpak 0.11.3, 0.11.7, 0.99.2

Various fixes mainly for flatpak

---

debian/control
usr/lib/linuxmint/mintinstall/installer/_flatpak.py
usr/lib/linuxmint/mintinstall/installer/cache.py
usr/lib/linuxmint/mintinstall/installer/dialogs.py
usr/lib/linuxmint/mintinstall/installer/installer.py
usr/lib/linuxmint/mintinstall/mintinstall.py

Clean up imports and exercise more caution when flatpak use is involved.
Only the _flatpak module will attempt to import it now, and behavior
elsewhere is adjusted when no remotes are found, including hiding the
flatpak category button.
Removed dependencies, added the necessary packages as recommends.
Mintinstall will need to be restarted once installing these packages
for support to live.  At this point a remote can be added successfully
via mimetype handler.
Fixes #192

all: Don't require flatpak to be installed.

---

usr/lib/linuxmint/mintinstall/installer/_apt.py

_apt.py: whitelist libimage-exiftool-perl

---

usr/lib/linuxmint/mintinstall/mintinstall.py

This change is for #226 .
At the center of mintinstall, Editors' Picks are already displayed with 12 tiles.
Therefore, I think that what is displayed in the Categories session is redundant information.
I think there is room at the end of Categories to respond to this issue.
I want to contribute to the Linux mint community.
This is my first pull request, so I'm not sure if this approach is correct.
Please ask for various opinions such as code reviews and advice.

Change Editors' Picks to All Applications (FR Issue#226)

---

usr/share/linuxmint/mintinstall/mintinstall.glade

Categories buttons and the top banner had a fixed size. They could only scale horizontally. Now they can also expand vertically, making the homescreen more responsive.
Preview attached below:

Update layout to expand vertically on homescreen

---

usr/lib/linuxmint/mintinstall/mintinstall.py
usr/share/linuxmint/mintinstall/mintinstall.glade

In the category and search views, the flowbox and buttons doesn't look
great. Escpecially in non-flat themes like Mint-X it can look overly busy.
Use a listbox for these views instead which gives a much cleaner and nicer
look.

UI: Use a listbox in some places instead of a flowbox

---

usr/lib/linuxmint/mintinstall/mintinstall.py
usr/share/linuxmint/mintinstall/mintinstall.glade

I centered the vertical text on the **category** buttons and **subcategories**.
Before:
After:
The remaining buttons are centered, and I don't know why they shouldn't be centered as well.
I added margins to the subcategories, similar to the example in XED, because there was a lack of top spacing, which helps visually by adding some symmetry.
Before:
After:

Improvements in appearance

---

usr/lib/linuxmint/mintinstall/mintinstall.py
usr/share/glib-2.0/schemas/com.linuxmint.install.gschema.xml

The setting allows the user to choose a preferred package type, or keep the current behavior of no filtering (the default). When enabled, search results for applications that are provided as both apt and Flatpak packages will be filtered to only show the preferred package type. As before, the type can still be changed on the package details page before installation. Applications that only have a single package will still be shown regardless of type.
I also fixed an issue I noticed with the sorting of search results. Previously, if a Flatpak package's display name and summary/description matched the search terms, but the ID did not, then it would have been ranked as if there was a match in the summary/description but not in the name. (E.g. search for "document viewer", and notice the …

Add a setting to filter apt/Flatpak results for the same application, with a fix for search sorting

---

usr/lib/linuxmint/mintinstall/mintinstall.py

Was getting this when clicking on slideshow dots
```Traceback (most recent call last):
File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1520, in on_dot_clicked
self.start_slideshow_timer(self.banner_stack, button.get_parent())
TypeError: Application.start_slideshow_timer() takes 1 positional argument but 3 were given

Fix dot click error

---

usr/lib/linuxmint/mintinstall/mintinstall.py

This PR solves the issue brought up in PR #382 (Code taken from PR #382 as well). The application `mintsources` is added to the Software Manager application in a sub-menu, and runs alongside the Software Manager without freezing the main window. At `mintsources` exit, we update the list of packages. It works as intended (tested on LM 22 VM), although it takes about two refreshes of the Software Manager to list the packages from an added repository (in the demo below, I used Brave's repository).
Testing:
1. Add repo into `mintsources` (launched from Software Manager submenu), update APT cache, and exit `mintsources`
2. Wait for Software Manager to refresh
3. Package from added repo should show up
Demo:

Add software sources into submenu (Adding code from PR #382)

---

usr/lib/linuxmint/mintinstall/mintinstall.py

Replaced manual resource management for the license file with the `with` statement to ensure it always gets closed. Additionally, since concatenating the results of `readlines()` reconstructs the original file content, `read() `is used directly instead for simplicity and efficiency.

Use auto resource management for license file

---

resources/mintinstall.glade
usr/lib/linuxmint/mintinstall/mintinstall.py

Hi!
Currently, the scrollbar position and margins of scrollable content vary between different views of the main GtkStack. Especially when not using overlay scrollbars, the scrollbars look a bit out of place compared to other XApps. I tried to improve the overall visual consistency by adjusting the widget spacing.
Before:
After:

Unify scrollbar positioning
